[package]
name = "rusttime"
version = "0.1.0"
authors = ["anders martini <andersmartini2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
dirs = "3.0.1"
chrono = "0.4.19"


